version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install -g pnpm
  pre_build:
    commands:
      - pnpm install --frozen-lockfile
  build:
    commands:
      - pnpm --filter pingo-backend run build
      - pnpm --filter pingo-backend deploy --prod ./out
      - cp -r pingo-backend/dist out/dist
      - cp Procfile out/
      - ls out
      - test -d out/node_modules/@nestjs/core
artifacts:
  base-directory: out
  files:
    - '**/*'

cache:
  paths:
    - '/root/.local/share/pnpm/store/**/*'