version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install -g pnpm
  pre_build:
    commands:
      - pnpm install --frozen-lockfile
  build:
    commands:
      - pnpm --filter pingo-backend run build
      - mkdir -p out
      - cp -r pingo-backend/dist out/dist
      - cp pingo-backend/package.json out/package.json
      - cp Procfile out/Procfile
      - (cd out && npm install --omit=dev)
      - ls out/node_modules/@nestjs/core
      - ls -la out

artifacts:
  base-directory: out
  files:
    - '**/*'

cache:
  paths:
    - '/root/.local/share/pnpm/store/**/*'